Repository brewsci/homebrew-bio, pull requests merged in 2018-03, with the labels that each got.

#80 shovill 0.9.0
  Formula/shovill.rb
Labels: help wanted, new formula

#81 bandage: Add a test
  Formula/bandage.rb
Labels: enhancement

#96 fwdpp: Boost is a build dependency
  Formula/fwdpp.rb
Labels: enhancement

#107 artemis 17.0.1
  Formula/artemis.rb
Labels: migrate

#138 fix bottle section i forgot
  Formula/clustal-w.rb
Labels: bug

#139 add missing 'cite' keyword
  Formula/clustal-omega.rb
Labels: bug

#153 readseq 2.1.30
  Formula/readseq.rb
Labels: migrate

#163 CircleCI: Increase no_output_timeout to 20m
  .circleci/config.yml
Labels: enhancement

#167 kmc: Does not depend on gcc and fix bottle block
  Formula/kmc.rb
Labels: bug

#175 minced: fix bottle block
  Formula/minced.rb
Labels: bug

#184 CircleCI: Add test-bot --root-url
  .circleci/config.yml
Labels: bug
