Repository brewsci/homebrew-bio, pull requests merged in 2019-07, with the labels that each got.

#683 circle: use xcode 9.2
  .circleci/config.yml
Labels: enhancement

#699 transdecoder: Fix Unsupported type NilClass for nil
  Formula/transdecoder.rb
Labels: bug

#712 gatk 4.1.2.0
  Formula/gatk.rb
Labels: new version
