Repository brewsci/homebrew-bio, pull requests merged in 2020-04, with the labels that each got.

#975 souporcell 2.0 (new formula)
  Formula/souporcell.rb
Labels: new formula

#976 ivar 1.2
  Formula/ivar.rb
Labels: new version

#977 ntedit 1.3.2
  Formula/ntedit.rb
Labels: new version

#978 kraken2 2.0.9
  Formula/kraken2.rb
Labels: new version

#979 hh-suite 3.2.0 (new formula)
  Formula/hh-suite.rb
Labels: new formula

#981 hh-suite: Improve style
  Formula/hh-suite.rb
Labels: enhancement

#982 bcalm 2.2.2
  Formula/bcalm.rb
Labels: new version

#983 trinity 2.8.6
  Formula/trinity.rb
Labels: new version

#986 ntjoin: bump revision
  Formula/ntjoin.rb
Labels: revision

#985 easel 0.46
  Formula/easel.rb
Labels: new version

#989 Fix style of 22 formulae
  Formula/artemis.rb
  Formula/bowtie.rb
  Formula/breseq.rb
  Formula/cd-hit.rb
  Formula/dida.rb
  Formula/easel.rb
  Formula/gatk.rb
  Formula/gepard.rb
  Formula/gzstream.rb
  Formula/jspecies.rb
  Formula/kaiju.rb
  Formula/kent-tools.rb
  Formula/mir-prefer.rb
  Formula/ngmerge.rb
  Formula/nxrepair.rb
  Formula/oases.rb
  Formula/quickmerge.rb
  Formula/taxonkit.rb
  Formula/varsim.rb
  Formula/vcf2phylip.rb
  Formula/wiggletools.rb
  Formula/xmatchview.rb
Labels: bug

#990 upload-bottles.yml: Use pr-upload
  .github/workflows/upload-bottles.yml
Labels: bug

#992 build-bottles.yml: Fix jonchang/audit-action
  .github/workflows/build-bottles.yml
Labels: bug

#993 bowtie: Use Python 3
  Formula/bowtie.rb
Labels: bug

#994 wiggletools: Remove uses_from_macos "python@2"
  Formula/wiggletools.rb
Labels: bug

#995 mosdepth 0.2.9
  Formula/mosdepth.rb
Labels: new version

#997 vcf2phylip: Use Python 3
  Formula/vcf2phylip.rb
Labels: bug

#980 Remove python@2 from gatk formula
  Formula/gatk.rb
Labels: bug

#998 build-bottles.yml: Add test-bot --cleanup on macOS
  .github/workflows/build-bottles.yml
  .github/workflows/deploy-formula-json.yml
Labels: bug

#984 salmon 1.2.1
  Formula/salmon.rb
Labels: new version

#1001 ngmerge 0.3
  Formula/ngmerge.rb
Labels: new version

#999 hisat2 2.2.0
  Formula/hisat2.rb
Labels: new version

#1000 xmatchview 1.2.3
  Formula/xmatchview.rb
Labels: new version

#1002 gatk 4.1.7.0
  Formula/gatk.rb
Labels: new version
