Repository brewsci/homebrew-bio, pull requests merged in 2020-10, with the labels that each got.

#1151 tigmint 1.2.1
  Formula/tigmint.rb
Labels: new version

#1163 ntcard 1.2.2
  Formula/ntcard.rb
Labels: new version

#1164 raptor 1.0.1 (new formula)
  Formula/raptor.rb
Labels: new formula

#1152 ivar 1.2.3
  Formula/ivar.rb
Labels: new version

#1169 xmatchview 1.2.5
  Formula/xmatchview.rb
Labels: new version

#1170 bowtie 1.3.0
  Formula/bowtie.rb
Labels: new version

#1175 kma 1.3.6
  Formula/kma.rb
Labels: new version

#1177 last 1133
  Formula/last.rb
Labels: new version

#1178 mosdepth 0.3.1
  Formula/mosdepth.rb
Labels: new version

#1171 busco 4.1.4
  Formula/busco.rb
Labels: new version

#1179 mothur 1.44.3
  Formula/mothur.rb
Labels: new version

#1180 pymol: update 2.4.0
  Formula/pymol.rb
Labels: new version

#1165 seqan3 3.0.2
  Formula/seqan@3.rb
Labels: new version

#1181 seqkit 0.14.0
  Formula/seqkit.rb
Labels: new version

#1182 taxonkit 0.6.1
  Formula/taxonkit.rb
Labels: new version

#1184 arcs: Bump revision for gcc@9
  Formula/arcs.rb
Labels: bug, revision
