Repository brewsci/homebrew-bio, pull requests merged in 2020-03, with the labels that each got.

#927 bifrost 1.0
  Formula/bifrost.rb
Labels: new formula

#928 vcf2phylip 2.0
  Formula/vcf2phylip.rb
Labels: new formula

#926 Lsd2 1.4.2.2
  Formula/lsd2.rb
Labels: enhancement, new version

#930 snp-dists 0.7.0
  Formula/snp-dists.rb
Labels: new version

#934 kounta 0.2.3
  Formula/kounta.rb
Labels: new version

#933 cannoli 0.9.0
  Formula/cannoli.rb
Labels: new version

#932 adam 0.31.0
  Formula/adam.rb
Labels: new version

#939 samclip 0.3
  Formula/samclip.rb
Labels: new version

#940 flye 2.7
  Formula/flye.rb
Labels: help wanted, new version

#942 nanopolish 0.12.0
  Formula/nanopolish.rb
Labels: new version

#943 build-bottles.yml: Add jonchang/audit-action
  .github/workflows/build-bottles.yml
Labels: enhancement

#944 samclip 0.4.0
  Formula/samclip.rb
Labels: new version

#945 bifrost 1.0.1
  Formula/bifrost.rb
Labels: new version

#947 snippy 4.6.0
  Formula/snippy.rb
Labels: new version

#948 dsh-bio 1.3.2
  Formula/dsh-bio.rb
Labels: new version

#953 masurca 3.3.9
  Formula/masurca.rb
Labels: new version

#951 skesa 2.4.0
  Formula/skesa.rb
Labels: new version

#956 shovill 1.1.0
  Formula/shovill.rb
Labels: new version

#952 delly 0.8.3
  Formula/delly.rb
Labels: new formula

#958 fasta 36.3.8h
  Formula/fasta.rb
Labels: new version

#965 ivar 1.1
  Formula/ivar.rb
Labels: new formula

#964 bifrost 1.0.3
  Formula/bifrost.rb
Labels: new version

#971 abricate 1.0.0
  Formula/abricate.rb
Labels: new version

#970 rasusa 0.2.0
  Formula/rasusa.rb
Labels: new version

#966 ntjoin 1.0.2
  Formula/ntjoin.rb
Labels: new version

#893 infernal 1.1.3
  Formula/infernal.rb
Labels: new version

#972 gatk 4.1.6.0
  Formula/gatk.rb
Labels: new version

#309 discovardenovo: import from brewsci/science
  Formula/discovardenovo.rb
Labels: migrate
