Repository brewsci/homebrew-bio, pull requests merged in 2020-07, with the labels that each got.

#1025 gfakluge 1.1.2
  Formula/gfakluge.rb
Labels: new version

#1024 ntjoin 1.0.3
  Formula/ntjoin.rb
Labels: new version

#1073 trinity 2.9.1
  Formula/trinity.rb
Labels: new version

#1026 salmon 1.3.0
  Formula/salmon.rb
Labels: new version

#1023 seqkit-0.13.0
  Formula/seqkit.rb
Labels: new version

#1072 seqkit 0.13.1
  Formula/seqkit.rb
Labels: new version

#1027 abricate 1.0.1
  Formula/abricate.rb
Labels: new version

#1077 abricate 1.0.1
  Formula/abricate.rb
Labels: enhancement

#1071 parasail 2.4.2
  Formula/parasail.rb
Labels: new version

#1070 nonpareil 3.3.4
  Formula/nonpareil.rb
Labels: new version

#1068 ngmaster 0.5.6
  Formula/ngmaster.rb
Labels: new version

#1074 seqkit 0.13.2
  Formula/seqkit.rb
Labels: new version

#1078 dsh-bio 1.3.3
  Formula/dsh-bio.rb
Labels: new version

#1066 mlst 2.19.0
  Formula/mlst.rb
Labels: new version

#1069 nanofilt 2.7.1
  Formula/nanofilt.rb
Labels: new version

#1028 bbtools 38.86
  Formula/bbtools.rb
Labels: new version

#1033 busco 4.1.1
  Formula/busco.rb
Labels: new version

#1037 cutadapt 2.10
  Formula/cutadapt.rb
Labels: new version

#1041 flye 2.7.1
  Formula/flye.rb
Labels: new version

#1029 beast2 2.6.2
  Formula/beast2.rb
Labels: new version

#1030 berokka 0.2.3
  Formula/berokka.rb
Labels: new version

#1031 bracken 2.6.0
  Formula/bracken.rb
Labels: new version

#1032 breseq 0.35.1
  Formula/breseq.rb
Labels: new version

#1035 crumble 0.8.3
  Formula/crumble.rb
Labels: new version

#1038 dehomopolymerate 0.4.0
  Formula/dehomopolymerate.rb
Labels: new version

#1036 das_tool 1.1.2
  Formula/das_tool.rb
Labels: new version

#1040 epa-ng 0.3.7
  Formula/epa-ng.rb
Labels: new version

#1043 gappa 0.6.0
  Formula/gappa.rb
Labels: new version

#1044 genome-painter 0.0.8
  Formula/genome-painter.rb
Labels: new version

#1045 groot 1.1.2
  Formula/groot.rb
Labels: new version

#1047 abyss-explorer 2.1.0
  Formula/abyss-explorer.rb
Labels: new version

#1049 kaiju 1.7.3
  Formula/kaiju.rb
Labels: new version

#1050 kma 1.3.0
  Formula/kma.rb
Labels: new version

#1051 kalign 3.2.3
  Formula/kalign.rb
Labels: new version

#1052 kssd 1.1
  Formula/kssd.rb
Labels: new version

#1053 lastz 1.04.03
  Formula/lastz.rb
Labels: new version

#1058 mapcaller 0.9.9.39
  Formula/mapcaller.rb
Labels: new version

#1054 libgff 2.0.0
  Formula/libgff.rb
Labels: new version

#1048 jellyfish 2.3.0
  Formula/jellyfish.rb
Labels: new version

#1061 maxbin2 2.2.7
  Formula/maxbin2.rb
Labels: new version

#1062 metabat 2.15
  Formula/metabat.rb
Labels: new version

#1059 masurca 3.4.1
  Formula/masurca.rb
Labels: new version

#1079 adam 0.32.0
  Formula/adam.rb
Labels: new version

#1080 cannoli 0.10.0
  Formula/cannoli.rb
Labels: new version

#1081 dsh-bio 1.3.4
  Formula/dsh-bio.rb
Labels: new version

#1083 fwdpp: revision bump for gsl
  Formula/fwdpp.rb
Labels: revision

#1057 lsd2 1.7.1
  Formula/lsd2.rb
Labels: new version

#1046 iqtree 2.0.6
  Formula/iqtree.rb
Labels: new version

#1055 libsequence 1.9.8
  Formula/libsequence.rb
Labels: new version

#1056 lighter 1.1.2
  Formula/lighter.rb
Labels: new version

#1034 bwa-mem2 2.0
  Formula/bwa-mem2.rb
Labels: new version

#1084 k8 0.2.5
  Formula/k8.rb
Labels: new version

#1085 minigraph 0.10
  Formula/minigraph.rb
Labels: new version

#1086 kma 1.3.2
  Formula/kma.rb
Labels: new version

#1087 phyml 3.3.20200621
  Formula/phyml.rb
Labels: new version

#1089 bifrost 1.0.4
  Formula/bifrost.rb
Labels: new version

#1092 vcf2phylip 2.3
  Formula/vcf2phylip.rb
Labels: new version

#1093 varsim 0.8.4
  Formula/varsim.rb
Labels: new version

#1095 subread 2.0.1
  Formula/subread.rb
Labels: new version

#1097 stringtie 2.1.4
  Formula/stringtie.rb
Labels: new version

#1099 squeakr 0.7
  Formula/squeakr.rb
Labels: linux_only, new version

#1100 seqan@3 3.0.1
  Formula/seqan@3.rb
Labels: new version

#1101 samblaster 0.1.26
  Formula/samblaster.rb
Labels: new version

#1103 rtg-tools 3.11
  Formula/rtg-tools.rb
Labels: new version

#1091 vsearch: migrate to Homebrew/core (# 1091)
  Formula/vsearch.rb
  tap_migrations.json
Labels: migrate

#1094 unikmer 0.11.0
  Formula/unikmer.rb
Labels: new version

#1106 pirate 1.0.4
  Formula/pirate.rb
Labels: new version

#1112 nanofilt: update source url (# 1112)
  Formula/nanofilt.rb
Labels: bug

#1113 cutadapt: update source urls (# 1113)
  Formula/cutadapt.rb
Labels: bug

#1108 fwdpp 0.8.1
  Formula/fwdpp.rb
Labels: new version

#1111 iqtree2 2.0.6 (new formula)
  Formula/iqtree2.rb
Labels: new formula

#1114 kent-tools 400
  Formula/kent-tools.rb
Labels: new version

#1116 kent-tools 401
  Formula/kent-tools.rb
Labels: new version

#1104 rcorrector 1.0.4
  Formula/rcorrector.rb
Labels: new version

#1117 upgrade gatk to 4.1.8.1
  Formula/gatk.rb
Labels: new version

#1120 iqtree2 2.0.7
  Formula/iqtree2.rb
Labels: new version

#1088 fastani 1.31
  Formula/fastani.rb
Labels: new version

#1096 staden-io-lib 1.14.13
  Formula/staden-io-lib.rb
Labels: new version

#1102 sambamba 0.7.1
  Formula/sambamba.rb
Labels: in progress, new version

#1125 roary: revision bump for perl
  Formula/roary.rb
Labels: revision

#1126 unicycler: revision bump for python
  Formula/unicycler.rb
Labels: revision

#1107 parsnp 1.5.2
  Formula/libmuscle.rb
  Formula/parsnp.rb
Labels: new version

#1105 racon 1.4.13
  Formula/racon.rb
Labels: new version
