Repository brewsci/homebrew-bio, pull requests merged in 2020-05, with the labels that each got.

#1003 taxonkit-0.6.0
  Formula/taxonkit.rb
Labels: new version

#1007 ivar 1.2.2
  Formula/ivar.rb
Labels: new version

#1006 r2r 1.0.6 (new formula)
  Formula/r2r.rb
Labels: new formula

#1010 build-bottles.yml: Run brew update-reset on Linux
  .github/workflows/build-bottles.yml
Labels: bug

#1009 last 1061
  Formula/last.rb
Labels: new version

#1012 .github: Use Docker image homebrew/ubuntu16.04
  .github/workflows/build-bottles.yml
  .github/workflows/upload-bottles.yml
Labels: enhancement
