Repository brewsci/homebrew-bio, pull requests merged in 2020-08, with the labels that each got.

#1130 sga: update patch url
  Formula/sga.rb
Labels: bug

#1131 canu: update homepage
  Formula/canu.rb
Labels: bug

#1121 flowcraft: revision bump for python@3.8
  Formula/flowcraft.rb
Labels: revision

#1123 fasttree: replace gcc dependency with libomp
  Formula/fasttree.rb
Labels: revision

#1119 nextflow 20.07.1
  Formula/nextflow.rb
Labels: new version

#1098 star-aligner 2.7.5b
  Formula/star-aligner.rb
Labels: new version

#1132 flye 2.8
  Formula/flye.rb
Labels: new version

#1118 beast2 2.6.3
  Formula/beast2.rb
Labels: new version

#1133 breseq 0.35.2
  Formula/breseq.rb
Labels: new version

#1067 mothur 1.44.2
  Formula/mothur.rb
Labels: new version

#1063 minced 0.4.2
  Formula/minced.rb
Labels: new version

#1134 kat: disable unsupported compiler flags on macOS
  Formula/kat.rb
Labels: revision

#1090 trinity 2.11.0
  Formula/trinity.rb
Labels: new version

#1060 matplotlib 2.2.5
  Formula/matplotlib.rb
Labels: new version

#1136 kma 1.3.3
  Formula/kma.rb
Labels: new version

#1138 gappa 0.6.1
  Formula/gappa.rb
Labels: new version

#1139 workflows: add update-develop
  .github/workflows/update-develop.yml
Labels: enhancement

#1140 ghostz: replace gcc with libomp
  Formula/ghostz.rb
Labels: revision

#1141 cd-hit: replace gcc with libomp
  Formula/cd-hit.rb
Labels: revision

#1142 e-mem: replace gcc with libomp
  Formula/e-mem.rb
Labels: revision

#1143 genome-painter: replace gcc with libomp
  Formula/genome-painter.rb
Labels: revision

#1144 star-aligner 2.7.5c
  Formula/star-aligner.rb
Labels: new version

#1148 bwa-mem2: delete sha256 stanza
  Formula/bwa-mem2.rb
Labels: bug

#1147 biobloomtools 2.3.3
  Formula/biobloomtools.rb
Labels: new version

#1149 Update edirect formula to version 13.8
  Formula/edirect.rb
Labels: new version
