Repository brewsci/homebrew-bio, pull requests merged in 2020-11, with the labels that each got.

#1187 taxonkit 0.6.2
  Formula/taxonkit.rb
Labels: new version

#1188 hh-suite 3.3.0
  Formula/hh-suite.rb
Labels: new version

#1190 bbtools 38.87
  Formula/bbtools.rb
Labels: new version

#1146 gffcompare 0.12.1 (new formula)
  Formula/gffcompare.rb
Labels: new formula

#1193 build-bottles.yml: Add --skip-recursive-dependents
  .github/workflows/build-bottles.yml
Labels: bug

#1194 breseq 0.35.4
  Formula/breseq.rb
Labels: new version

#1159 bifrost 1.0.5
  Formula/bifrost.rb
Labels: new version

#1196 kaiju 1.7.4
  Formula/kaiju.rb
Labels: new version

#1197 epa-ng 0.3.8
  Formula/epa-ng.rb
Labels: new version

#1198 fastani 1.32
  Formula/fastani.rb
Labels: new version

#1199 ivar 1.3
  Formula/ivar.rb
Labels: new version

#1200 kalign 3.3
  Formula/kalign.rb
Labels: new version

#1201 kraken2 2.1.1
  Formula/kraken2.rb
Labels: new version

#1189 hssp 3.1.5 (new formula)
  Formula/hssp.rb
Labels: new formula

#1192 dssp 3.1.4 (new formula)
  Formula/dssp.rb
Labels: new formula

#1195 xssp: update to 3.0.10 and deprecate
  Formula/xssp.rb
Labels: new version

#1205 ntjoin 1.0.4
  Formula/ntjoin.rb
Labels: new version

#1206 dsh-bio 1.4
  Formula/dsh-bio.rb
Labels: new version

#1203 upload-bottles.yml: check for `ci-skip-upload` label
  .github/workflows/upload-bottles.yml
Labels: ci-skip-upload

#1208 upload-bottles.yml: fix upload skip
  .github/workflows/upload-bottles.yml
Labels: ci-skip-upload

#1209 upload-bottles.yml: actually fix upload skip
  .github/workflows/upload-bottles.yml
Labels: ci-skip-upload

#1210 upload-bottles.yml: set `shell` to `bash`
  .github/workflows/upload-bottles.yml
Labels: ci-skip-upload

#1207 xssp: move `deprecate!` to after `bottle`
  Formula/xssp.rb
Labels: ci-skip-upload

#1204 bmdca 0.8.12 (new formula)
  Formula/bmdca.rb
Labels: new formula

#1211 ntjoin 1.0.5
  Formula/ntjoin.rb
Labels: new version

#1212 ntedit 1.3.3
  Formula/ntedit.rb
Labels: new version

#1215 Depend on openjdk rather than :java
  Formula/abyss-explorer.rb
  Formula/artemis.rb
  Formula/astral.rb
  Formula/bazam.rb
  Formula/bbtools.rb
  Formula/beast2.rb
  Formula/cluster-picker.rb
  Formula/dsh-bio.rb
  Formula/figtree.rb
  Formula/gatk.rb
  Formula/gepard.rb
  Formula/jspecies.rb
  Formula/mhap.rb
  Formula/minced.rb
  Formula/nextflow.rb
  Formula/pathvisio.rb
  Formula/pilon.rb
  Formula/realphy.rb
  Formula/rtg-tools.rb
  Formula/sepp.rb
  Formula/snpeff.rb
  Formula/trimmomatic.rb
  Formula/trinity.rb
  Formula/varscan.rb
  Formula/varsim.rb
  Formula/webin-cli.rb
Labels: bug, ci-skip-upload, java
