Repository brewsci/homebrew-bio, pull requests merged in 2020-12, with the labels that each got.

#1217 pymol: update 2.4.0 bottle.
  Formula/pymol.rb
Labels: bottles, ci-skip-upload, macos-issue

#1220 CI: Set HOMEBREW_FORCE_VENDOR_RUBY=1 for macOS
  .github/workflows/build-bottles.yml
Labels: bug, ci-skip-upload

#1202 percolator 3.05 (new formula)
  Formula/percolator.rb
Labels: new formula

#1219 tmalign 20190822 (new formula)
  Formula/tmalign.rb
Labels: new formula

#1218 ntedit 1.3.4
  Formula/ntedit.rb
Labels: new version

#1221 mican 20191127 (new formula)
  Formula/mican.rb
Labels: new formula

#1223 oma 2.4.2
  Formula/oma.rb
Labels: new version
