Repository brewsci/homebrew-bio, pull requests merged in 2020-02, with the labels that each got.

#882 racon 1.4.3
  .github/workflows/upload-bottles.yml
Labels: new version

#853 busco: fix config path
  Formula/busco.rb
Labels: bug

#896 kraken 1.1.1
  Formula/kraken.rb
Labels: new-version

#897 last 1047
  Formula/last.rb
Labels: new-version

#898 masurca 3.3.5
  Formula/masurca.rb
Labels: new version

#902 mapcaller 0.9.9.34
  Formula/mapcaller.rb
Labels: new version

#904 mapcaller 0.9.9.37
  Formula/mapcaller.rb
Labels: new version

#909 prokka 1.14.6 + tbl2asn 25.8
  Formula/prokka.rb
  Formula/tbl2asn.rb
Labels: new version

#911 abricate 0.9.9
  Formula/abricate.rb
Labels: new version

#912 finch 0.3.0
  Formula/finch-rs.rb
Labels: new version

#913 freebayes 1.3.2 + snippy 4.5.0 + snp-sites
  Formula/freebayes.rb
  Formula/snippy.rb
  Formula/snp-sites.rb
Labels: new version

#910 nullarbor 2.0.20191013
  Formula/nullarbor.rb
Labels: ci_error, macos_issue, new formula

#916 wiggletools: Bump revision for htslib, fix python2
  Formula/wiggletools.rb
Labels: revision

#920 libgff 1.2
  Formula/libgff.rb
Labels: new formula

#921 vmatch 2.3.1
  Formula/vmatch.rb
Labels: binaries_only, new formula

#922 legsta 0.5.1
  Formula/legsta.rb
Labels: new version

#919 megahit 1.2.9
  Formula/megahit.rb
Labels: new version

#923 racon 1.4.10
  Formula/racon.rb
Labels: new version
