Repository brewsci/homebrew-bio, pull requests merged in 2021-03, with the labels that each got.

#1300 viennarna 2.4.17
  Formula/viennarna.rb
Labels: new version

#1292 gatk 4.2.0.0
  Formula/gatk.rb
Labels: new version

#1302 paml 4.9j
  Formula/paml.rb
Labels: new version

#1306 maxbin2: Fix the test
  Formula/maxbin2.rb
Labels: bug, ci-skip-upload

#1305 idba: Bump revision for gcc@9
  Formula/idba.rb
Labels: bug

#1304 busco 5.0.0
  Formula/busco.rb
Labels: new version

#1259 kat 2.4.2
  Formula/kat.rb
Labels: new version

#1307 jmol 14.31.34
  Formula/jmol.rb
Labels: new version

#1311 cannoli 0.12.0
  Formula/cannoli.rb
Labels: new version

#1310 adam 0.34.0
  Formula/adam.rb
Labels: new version

#1312 dsh-bio 2.0.3
  Formula/dsh-bio.rb
Labels: new version

#1314 cutadapt 3.3
  Formula/cutadapt.rb
Labels: new version

#1315 flye 2.8.3
  Formula/flye.rb
Labels: new version

#1323 wiggletools 1.2.10
  Formula/wiggletools.rb
Labels: new version

#1301 krona 2.8 (new formula)
  Formula/krona.rb
Labels: new formula

#1317 nanofilt 2.8.0
  Formula/nanofilt.rb
Labels: new version
