Repository brewsci/homebrew-bio, pull requests merged in 2021-02, with the labels that each got.

#1265 jmol 14.31.29
  Formula/jmol.rb
Labels: new version

#1266 slim v3.5 (new formula)
  Formula/slim.rb
Labels: new formula

#1269 ntjoin 1.0.6
  Formula/ntjoin.rb
Labels: new version

#1272 bali-phy 3.6.0
  Formula/bali-phy.rb
Labels: new version

#1271 jmol 14.31.32
  Formula/jmol.rb
Labels: new version

#1277 falco 0.2.4 (new formula)
  Formula/falco.rb
Labels: new formula

#1278 faqcs 2.10 (new formula)
  Formula/faqcs.rb
Labels: new formula

#1280 Use HOMEBREW_GITHUB_ACTIONS rather than CI
  Formula/abyss-explorer.rb
  Formula/jmol.rb
Labels: bug, ci-skip-upload

#1279 raster3d 3.0-7 (new formula)
  Formula/raster3d.rb
Labels: new formula

#1281 mmdb2 2.0.20 (new formula)
  Formula/mmdb2.rb
Labels: new formula

#1282 libccp4 6.5.1 (new formula)
  Formula/libccp4.rb
Labels: new formula

#1283 ssm 1.4 (new formula)
  Formula/ssm.rb
Labels: new formula

#1287 Fix style: Ambiguous regexp literal
  Formula/astral.rb
  Formula/biomake.rb
  Formula/bioperl.rb
  Formula/fasttree.rb
  Formula/minimap2.rb
  Formula/mummer.rb
  Formula/nextflow.rb
  Formula/snpeff.rb
  Formula/trimadap.rb
Labels: bug, ci-skip-upload

#1286 Upload bottles to Archive.org
  .github/workflows/upload-bottles.yml
Labels: enhancement

#1284 dsh-bio 2.0.2
  Formula/dsh-bio.rb
Labels: new version

#1288 Change root-url to Archive.org
  .github/ISSUE_TEMPLATE.md
  .github/workflows/build-bottles.yml
  .github/workflows/upload-bottles.yml
  Formula/dsh-bio.rb
  LICENSE
  Makefile
  README.md
  _config.yml
Labels: bug

#1289 clipper 2.1.20180802 (new formula)
  Formula/clipper4coot.rb
Labels: new formula

#1293 CI: Upload bottles to Archive.org using pr-upload
  .github/workflows/build-bottles.yml
  .github/workflows/upload-bottles.yml
Labels: enhancement
