Repository brewsci/homebrew-bio, pull requests merged in 2021-04, with the labels that each got.

#1320 biointerchange 2.0.5 (new formula)
  Formula/biointerchange.rb
Labels: new formula

#1329 CI: Upload bottles to GitHub Packages
  .github/workflows/build-bottles.yml
  .github/workflows/upload-bottles.yml
Labels: enhancement

#1331 varscan 2.4.4
  Formula/varscan.rb
Labels: new version

#1333 CI: Use the GitHub Actions VM image for skopeo
  .github/workflows/upload-bottles.yml
Labels: bug

#1334 CI: Set HOMEBREW_FORCE_HOMEBREW_ON_LINUX=1
  .github/workflows/upload-bottles.yml
Labels: bug

#1335 CI: Run brew update
  .github/workflows/upload-bottles.yml
Labels: bug

#1338 varsim 0.8.6
  Formula/varsim.rb
Labels: new version

#1339 taxonkit-0.8.0
  Formula/taxonkit.rb
Labels: new version

#1340 minimap2 2.18
  Formula/minimap2.rb
Labels: new version

#1342 update seqkit to 0.16.0
  Formula/seqkit.rb
Labels: new version
