Repository brewsci/homebrew-bio, pull requests merged in 2021-01, with the labels that each got.

#1224 raptor 1.1.0
  Formula/raptor.rb
Labels: new version

#1230 emboss: always build without x11
  Formula/emboss.rb
Labels: ci-skip-upload

#1228 wiggletools 1.2.7
  Formula/wiggletools.rb
Labels: new version

#1232 adam 0.33.0
  Formula/adam.rb
Labels: new version

#1233 cannoli 0.11.1
  Formula/cannoli.rb
Labels: new version

#1237 phyx: fix style error
  Formula/phyx.rb
Labels: ci-skip-upload

#1238 wiggletools 1.2.8
  Formula/wiggletools.rb
Labels: new version

#1236 jmol 14.31.2 (new formula)
  Formula/jmol.rb
Labels: in progress, new formula

#1239 various formulae: add livecheck
  Formula/adam.rb
  Formula/ale.rb
  Formula/astral.rb
  Formula/bali-phy.rb
  Formula/bazam.rb
  Formula/bfc.rb
  Formula/bioperl.rb
  Formula/bmdca.rb
  Formula/bowtie.rb
  Formula/cannoli.rb
  Formula/centrifuge.rb
  Formula/circlator.rb
  Formula/easel.rb
  Formula/fasta.rb
  Formula/freebayes.rb
  Formula/gemma.rb
  Formula/harvest-tools.rb
  Formula/hisat2.rb
  Formula/iqtree.rb
  Formula/iva.rb
  Formula/k8.rb
  Formula/kat.rb
  Formula/kent-tools.rb
  Formula/minigraph.rb
  Formula/minimap2.rb
  Formula/mrbayes.rb
  Formula/nanopolish.rb
  Formula/nextflow.rb
  Formula/portcullis.rb
  Formula/salmid.rb
  Formula/sdsl-lite.rb
  Formula/sga.rb
  Formula/skesa.rb
  Formula/snpeff.rb
  Formula/vt.rb
  Formula/webin-cli.rb
Labels: ci-skip-upload, enhancement

#1241 various formulae: add livecheck (part 2)
  Formula/bodr.rb
  Formula/pplacer.rb
  Formula/treepl.rb
  Formula/trimadap.rb
  Formula/varscan.rb
Labels: ci-skip-upload, enhancement

#1243 seqkit-0.15.0
  Formula/seqkit.rb
Labels: new version

#1245 tigmint 1.2.2
  Formula/tigmint.rb
Labels: new version

#1246 jmol 14.31.25
  Formula/jmol.rb
Labels: new version

#1250 dsh-bio 2.0
  Formula/dsh-bio.rb
Labels: new version

#1251 jmol: test for java.awt.HeadlessException
  Formula/jmol.rb
Labels: ci-skip-upload

#1254 taxonkit-0.7.1
  Formula/taxonkit.rb
Labels: new version

#1253 jmol 14.31.26
  Formula/jmol.rb
Labels: new version

#1242 gfaview: deprecate
  Formula/gfaview.rb
Labels: ci-skip-upload

#1255 plink2: import from brewsci/science
  Formula/plink2.rb
Labels: migrate, new formula

#1256 taxonkit-0.7.2
  Formula/taxonkit.rb
Labels: new version

#1258 jmol 14.31.28
  Formula/jmol.rb
Labels: new version

#1249 matplotlib 3.3.4
  Formula/kat.rb
  Formula/matplotlib.rb
Labels: new version
