Repository brewsci/homebrew-bio, pull requests merged in 2021-06, with the labels that each got.

#1336 pathvisio: Update the description
  Formula/pathvisio.rb
Labels: build failure, ci-skip-upload, enhancement

#1360 arcs 1.2.2
  Formula/arcs.rb
Labels: new version

#1362 tigmint 1.2.3
  Formula/tigmint.rb
Labels: new version

#1369 arcs: Remove dependency on links-scaffolder
  Formula/arcs.rb
Labels: ci-skip-upload

#1371 xssp: Add deprecation date
  Formula/xssp.rb
Labels: bug, ci-skip-upload

#1368 ntjoin 1.0.7
  Formula/ntjoin.rb
Labels: new version

#1372 ntlink 1.0.1 (new formula)
  Formula/ntlink.rb
Labels: new formula

#1373 jmol 14.31.43
  Formula/jmol.rb
Labels: new version
