Repository brewsci/homebrew-bio, pull requests merged in 2021-09, with the labels that each got.

#1351 pymol 2.5.0
  Formula/pymol.rb
Labels: new version

#1409 kollector: import from brewsci/science
  Formula/kollector.rb
Labels: migrate

#1416 arcs: Fix style
  Formula/arcs.rb
Labels: bug, hacktoberfest, ci-skip-upload

#1418 phyx: Fix style
  Formula/phyx.rb
Labels: bug, hacktoberfest, ci-skip-upload

#1419 mrbayes: Fix style
  Formula/mrbayes.rb
Labels: bug, hacktoberfest, ci-skip-upload
